import { createContext, useContext, useState, useEffect } from 'react'

const LangContext = createContext()

const translations = {
  en: {
    code: 'EN',
    dir: 'ltr',
    locale: 'en-US',
    findPerfectTime: 'Find the <accent>perfect time</accent>',
    createSubtitle: 'Create an event and share the link. No sign-up needed.',
    eventName: 'Event Name',
    description: 'Description',
    yourName: 'Your Name',
    dateFrom: 'From',
    dateTo: 'To',
    dateRange: 'Date range',
    email: 'Your Email',
    emailHint: 'Get notified of new responses',
    required: 'required',
    creating: 'Creating...',
    createEvent: 'Create Event',
    enterName: 'Enter your name to participate',
    continue: 'Continue',
    alreadyExists: 'already has a response. What would you like to do?',
    overwrite: 'Overwrite existing',
    createNew: 'Create new',
    back: 'Back',
    respondingAs: 'Responding as',
    changeName: 'Change name',
    comment: 'Comment',
    saving: 'Saving...',
    saveAvailability: 'Save',
    saved: 'Saved!',
    responses: 'Responses',
    showResults: 'Show Results',
    copyLink: 'Copy share link',
    copied: 'Copied!',
    backToEvent: 'Back to event',
    results: 'Results',
    summary: 'Results',
    response: 'response',
    responsePlural: 'responses',
    bestDays: 'Best Days',
    ideal: 'ideal',
    busy: 'busy',
    allParticipants: 'All Participants',
    backToHome: 'Back to home',
    howItWorks: 'How it works',
    neutral: 'Neutral',
    neutralDesc: 'Default state — available',
    busyLabel: 'Busy',
    busyDesc: "You can't make it this day",
    idealLabel: 'Ideal',
    idealDesc: 'This day works great for you',
    onboardingHint: 'Click any day on the calendar to cycle through these states.',
    gotIt: 'Got it',
    today: 'Today',
    by: 'By',
    copyright: 'Filip Rosa',
    markAllBusy: 'Mark all busy',
    clearAll: 'Clear all',
    vetoWarning: 'has conflicts',
    respond: 'Respond',
    overview: 'Overview',
    unsubscribed: 'You have been unsubscribed from notifications for this event.',
    onboardingStep1Title: 'Click = Available / Busy',
    onboardingStep1Desc: 'Tap a day to toggle between available and busy.',
    onboardingStep2Title: 'Double-click = Ideal',
    onboardingStep2Desc: 'Double-click (or long-press on mobile) to mark your best days.',
    onboardingEditTip: 'Tip: To edit a previous response, enter the exact same name.',
    onboardingAnimationPlaceholder: 'Animation preview will appear here',
    detailedResults: 'Detailed Results',
    dayNames: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun'],
    monthNames: ['January', 'February', 'March', 'April', 'May', 'June', 'July', 'August', 'September', 'October', 'November', 'December'],
  },
  cs: {
    code: 'CZ',
    dir: 'ltr',
    locale: 'cs-CZ',
    findPerfectTime: 'Najdi <accent>ideální čas</accent>',
    createSubtitle: 'Vytvoř událost a sdílej odkaz. Bez registrace.',
    eventName: 'Název události',
    description: 'Popis',
    yourName: 'Tvoje jméno',
    dateFrom: 'Od',
    dateTo: 'Do',
    dateRange: 'Rozsah dat',
    email: 'Tvůj email',
    emailHint: 'Dostaneš upozornění na nové odpovědi',
    required: 'povinné',
    creating: 'Vytvářím...',
    createEvent: 'Vytvořit událost',
    enterName: 'Zadej jméno pro účast',
    continue: 'Pokračovat',
    alreadyExists: 'už má odpověď. Co chceš udělat?',
    overwrite: 'Přepsat existující',
    createNew: 'Vytvořit novou',
    back: 'Zpět',
    respondingAs: 'Odpovídáš jako',
    changeName: 'Změnit jméno',
    comment: 'Komentář',
    saving: 'Ukládám...',
    saveAvailability: 'Uložit',
    saved: 'Uloženo!',
    responses: 'Odpovědi',
    showResults: 'Zobrazit výsledky',
    copyLink: 'Kopírovat odkaz',
    copied: 'Zkopírováno!',
    backToEvent: 'Zpět na událost',
    results: 'Výsledky',
    summary: 'Výsledky',
    response: 'odpověď',
    responsePlural: 'odpovědí',
    bestDays: 'Nejlepší dny',
    ideal: 'ideální',
    busy: 'zaneprázdněn',
    allParticipants: 'Všichni účastníci',
    backToHome: 'Zpět domů',
    howItWorks: 'Jak to funguje',
    neutral: 'Neutrální',
    neutralDesc: 'Výchozí stav — dostupný',
    busyLabel: 'Zaneprázdněn',
    busyDesc: 'Tento den nemůžeš',
    idealLabel: 'Ideální',
    idealDesc: 'Tento den ti vyhovuje',
    onboardingHint: 'Klikni na den v kalendáři pro přepínání stavů.',
    gotIt: 'Rozumím',
    today: 'Dnes',
    by: 'Od',
    copyright: 'Filip Rosa',
    markAllBusy: 'Vše zaneprázdněn',
    clearAll: 'Vymazat vše',
    vetoWarning: 'má konflikty',
    respond: 'Přidat odpověď',
    overview: 'Přehled',
    unsubscribed: 'Odhlásili jsme vás z notifikací pro tuto událost.',
    onboardingStep1Title: 'Klik = Dostupný / Zaneprázdněn',
    onboardingStep1Desc: 'Klikni na den pro přepnutí mezi dostupný a zaneprázdněn.',
    onboardingStep2Title: 'Dvojklik = Ideální',
    onboardingStep2Desc: 'Dvojklikem (nebo dlouhým stiskem na mobilu) označ své nejlepší dny.',
    onboardingEditTip: 'Tip: Pro úpravu předchozí odpovědi zadej stejné jméno.',
    onboardingAnimationPlaceholder: 'Zde se zobrazí náhled animace',
    detailedResults: 'Podrobné výsledky',
    dayNames: ['Po', 'Út', 'St', 'Čt', 'Pá', 'So', 'Ne'],
    monthNames: ['Leden', 'Únor', 'Březen', 'Duben', 'Květen', 'Červen', 'Červenec', 'Srpen', 'Září', 'Říjen', 'Listopad', 'Prosinec'],
  },
  he: {
    code: 'HE',
    dir: 'rtl',
    locale: 'he-IL',
    findPerfectTime: 'מצא את <accent>הזמן המושלם</accent>',
    createSubtitle: 'צור אירוע ושתף את הקישור. ללא הרשמה.',
    eventName: 'שם האירוע',
    description: 'תיאור',
    yourName: 'השם שלך',
    dateFrom: 'מ',
    dateTo: 'עד',
    dateRange: 'טווח תאריכים',
    email: 'האימייל שלך',
    emailHint: 'קבל הודעות על תגובות חדשות',
    required: 'חובה',
    creating: 'יוצר...',
    createEvent: 'צור אירוע',
    enterName: 'הזן את שמך להשתתפות',
    continue: 'המשך',
    alreadyExists: 'כבר יש תשובה. מה תרצה לעשות?',
    overwrite: 'דרוס קיים',
    createNew: 'צור חדש',
    back: 'חזור',
    respondingAs: 'מגיב בתור',
    changeName: 'שנה שם',
    comment: 'הערה',
    saving: 'שומר...',
    saveAvailability: 'שמור',
    saved: 'נשמר!',
    responses: 'תגובות',
    showResults: 'הצג תוצאות',
    copyLink: 'העתק קישור',
    copied: 'הועתק!',
    backToEvent: 'חזור לאירוע',
    results: 'תוצאות',
    summary: 'תוצאות',
    response: 'תגובה',
    responsePlural: 'תגובות',
    bestDays: 'הימים הטובים ביותר',
    ideal: 'אידיאלי',
    busy: 'עסוק',
    allParticipants: 'כל המשתתפים',
    backToHome: 'חזור הביתה',
    howItWorks: 'איך זה עובד',
    neutral: 'ניטרלי',
    neutralDesc: 'מצב ברירת מחדל — זמין',
    busyLabel: 'עסוק',
    busyDesc: 'לא יכול ביום הזה',
    idealLabel: 'אידיאלי',
    idealDesc: 'היום הזה מתאים מצוין',
    onboardingHint: 'לחץ על יום בלוח השנה כדי לעבור בין המצבים.',
    gotIt: 'הבנתי',
    today: 'היום',
    by: 'מאת',
    copyright: 'Filip Rosa',
    markAllBusy: 'סמן הכל עסוק',
    clearAll: 'נקה הכל',
    vetoWarning: 'יש התנגשויות',
    respond: 'להגיב',
    overview: 'סקירה',
    unsubscribed: 'בוטלה ההרשמה שלך להתראות עבור אירוע זה.',
    onboardingStep1Title: 'לחיצה = זמין / עסוק',
    onboardingStep1Desc: 'לחץ על יום כדי לעבור בין זמין ועסוק.',
    onboardingStep2Title: 'לחיצה כפולה = אידיאלי',
    onboardingStep2Desc: 'לחיצה כפולה (או לחיצה ארוכה בנייד) לסימון הימים הטובים ביותר.',
    onboardingEditTip: 'טיפ: כדי לערוך תשובה קודמת, הזן את אותו שם בדיוק.',
    onboardingAnimationPlaceholder: 'תצוגה מקדימה של אנימציה תופיע כאן',
    detailedResults: 'תוצאות מפורטות',
    dayNames: ['ב׳', 'ג׳', 'ד׳', 'ה׳', 'ו׳', 'ש׳', 'א׳'],
    monthNames: ['ינואר', 'פברואר', 'מרץ', 'אפריל', 'מאי', 'יוני', 'יולי', 'אוגוסט', 'ספטמבר', 'אוקטובר', 'נובמבר', 'דצמבר'],
  },
  mo: {
    code: 'MO',
    dir: 'ltr',
    locale: 'cs-CZ',
    findPerfectTime: 'Nandem <accent>ten správné čas</accent>, kamošu',
    createSubtitle: 'Udělé akcu, pošli odkaz a konec. Žádná registraca.',
    eventName: 'Jak se to bude menovat',
    description: 'Popisek',
    yourName: 'Jak ti řikajó',
    dateFrom: 'Od',
    dateTo: 'Do',
    dateRange: 'Období',
    email: 'Tvoj mejl',
    emailHint: 'Pošlem ti, jak někdo odpoví',
    required: 'musiš',
    creating: 'Čeké, dělám na tom...',
    createEvent: 'Udělat akcu',
    enterName: 'Napiš jak ti řikajó, ať víme kdo si',
    continue: 'Deme',
    alreadyExists: 'už tu něco napsal. Co s tym provedem?',
    overwrite: 'Přemazat to',
    createNew: 'Udělat novó',
    back: 'Zpátky',
    respondingAs: 'Teďka si',
    changeName: 'Změnit méno',
    comment: 'Kybic',
    saving: 'Čeké, ukládám to přecik...',
    saveAvailability: 'Uložit',
    saved: 'Uloženy.',
    responses: 'Co lidi napsali',
    showResults: 'Ukázat výsledky',
    copyLink: 'Zkopči odkaz',
    copied: 'Zkopiroval sem to!',
    backToEvent: 'Zpátky na akcu',
    results: 'Výsledky',
    summary: 'Shrnutí',
    response: 'odpověď',
    responsePlural: 'odpovědě',
    bestDays: 'Nejlepší dny',
    ideal: 'supr',
    busy: 'nasrat',
    allParticipants: 'Všickni',
    backToHome: 'Zpátky domu',
    howItWorks: 'Hele jak to funguje',
    neutral: 'Normálka',
    neutralDesc: 'Je mně to jedno, možu',
    busyLabel: 'Nemožu',
    busyDesc: 'Nepřindu ty, konino',
    idealLabel: 'Užasny',
    idealDesc: 'Tady by to bylo nejlepči',
    onboardingHint: 'Klikni na deň a přepni si to jak potřebuješ.',
    gotIt: 'Chápu, kamošu',
    today: 'Dneska',
    by: 'Od',
    copyright: 'Filip Rosa',
    markAllBusy: 'Všecko zaneprázdněn',
    clearAll: 'Vymazat všecko',
    vetoWarning: 'nesedi to',
    respond: 'Přidat odpověď',
    overview: 'Přehled',
    unsubscribed: 'Už ti nebudem posílat kdo odpovídá na tudle akcu.',
    onboardingStep1Title: 'Klik = Možu / Nemožu',
    onboardingStep1Desc: 'Klikni na den a přepni jestli možeš nebo ne.',
    onboardingStep2Title: 'Dvojklik = Supr',
    onboardingStep2Desc: 'Dvojklikem (nebo dlouze na mobilu) označ dny co ti sedijo nejlip.',
    onboardingEditTip: 'Fígl: Chceš upravit co si předtym napsal? Zadé stejný méno.',
    onboardingAnimationPlaceholder: 'Tady bude animačka',
    detailedResults: 'Detajlní výsledky',
    dayNames: ['Po', 'Út', 'St', 'Čt', 'Pá', 'So', 'Ne'],
    monthNames: ['Leden', 'Únor', 'Březen', 'Duben', 'Květen', 'Červen', 'Červenec', 'Srpen', 'Září', 'Říjen', 'Listopad', 'Prosinec'],
  },
}

const langOrder = ['cs', 'en', 'he', 'mo']

function detectLanguage() {
  if (typeof window === 'undefined') return 'cs'
  const stored = localStorage.getItem('lang')
  if (stored && translations[stored]) return stored

  const browserLangs = navigator.languages || [navigator.language || '']
  for (const bl of browserLangs) {
    const code = bl.toLowerCase()
    if (code.startsWith('cs') || code.startsWith('sk')) return 'cs'
    if (code.startsWith('he') || code.startsWith('iw')) return 'he'
    if (code.startsWith('en')) return 'en'
  }
  return 'cs'
}

export function LangProvider({ children }) {
  const [lang, setLang] = useState(detectLanguage)

  useEffect(() => {
    const dir = translations[lang]?.dir || 'ltr'
    document.documentElement.setAttribute('dir', dir)
  }, [lang])

  function cycleLang() {
    const i = langOrder.indexOf(lang)
    const next = langOrder[(i + 1) % langOrder.length]
    setLang(next)
    localStorage.setItem('lang', next)
  }

  const t = translations[lang] || translations.cs

  return (
    <LangContext.Provider value={{ lang, t, cycleLang }}>
      {children}
    </LangContext.Provider>
  )
}

export function useLang() {
  return useContext(LangContext)
}
